apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:        
        tier: nginx
    spec:
      containers:
      - name: myapp
        image: wangyanglinux/myapp:v1
        ports:
        - containerPort: 80
