g++ redis.cc    EventLoop.cc    -g  ./util/status.cc    -lpthread   dataBase.cc redisPersistence.cc Epoll.c Channel.cc  Accept.cc   Buffer.cc   Server.cc   InetAddress.cc  SocketOpts.cc   Socket.cc


